version: "3"

services:
  web:
    build: .
    restart: always
    links:
      - db
      - redis
    environment:
      NODE_ENV: development
      MISSKEY_url: http://localhost:3000/
      MISSKEY_port: 3000
      MISSKEY_db_host: db
      MISSKEY_db_port: 5432
      MISSKEY_db_db: misskey
      MISSKEY_db_user: misskey
      MISSKEY_db_pass: misskey
      MISSKEY_redis_host: redis
      MISSKEY_redis_port: 6379
      MISSKEY_id: aid
      MISSKEY_objectStorage_baseUrl: http://localhost:9000/misskey
      MISSKEY_objectStorage_useSSL: false
      MISSKEY_objectStorage_s3ForcePathStyle: true
      MISSKEY_objectStorage_endpoint: minio:9000
      MISSKEY_objectStorage_bucket: misskey
      MISSKEY_objectStorage_prefix: files
      MISSKEY_objectStorage_accessKey: misskey
      MISSKEY_objectStorage_secretKey: misskeymisskey
    ports:
      - "3000:3000"
    networks:
      - internal_network
      - external_network

  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    volumes:
      - redis:/data

  db:
    restart: always
    image: postgres:12.2-alpine
    networks:
      - internal_network
    environment:
      POSTGRES_DB: misskey
      POSTGRES_USER: misskey
      POSTGRES_PASSWORD: misskey
    volumes:
      - db:/var/lib/postgresql/data

  minio:
    restart: always
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    networks:
      - internal_network
      - external_network
    environment:
      MINIO_ROOT_USER: misskey
      MINIO_ROOT_PASSWORD: misskeymisskey
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

networks:
  internal_network:
    internal: true
  external_network:

volumes:
  db: {}
  redis: {}
  minio: {}
